spring:
  ai:
    deepseek:
      api-key: your api key
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 0.2

    openai:
      base-url: your base url
      api-key: your api key
      chat:
        options:
          model: deepseek-chat
          temperature: 0.2